### ISSUE TITLE
Headers sometimes don't get written to CSV file

### ISSUE THREAD

**Issue by erkghlerngm44** [erkghlerngm44/r-anime-soulmate-finder#7]
`file.tell()` sometimes evals to `True` when the headers haven't actually been written to file, which causes a few dodgy exceptions when trying to sort the file (or reading off of it to get the usernames to add to `processed`)

**Tracebacks:**

When running it normally:
```
(venv)erkghlerngm44:~/workspace/r-anime-soulmate-finder (master) $ python3 -m soulmate_finder USER --ftf 15 --quiet --buffer-size 1024
Retrieving comment ids for FTF: Free Talk Fridays - Week of September 08, 2017 (6yr7ff)
...
Retrieving comment ids for FTF: Free Talk Fridays - Week of June 02, 2017 (6eqwxj)
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/workspace/r-anime-soulmate-finder/soulmate_finder/__main__.py", line 293, in <module>
    main(comments, **vars(args))
  File "/home/ubuntu/workspace/r-anime-soulmate-finder/soulmate_finder/__main__.py", line 202, in main
    reverse=True)
  File "/home/ubuntu/workspace/r-anime-soulmate-finder/soulmate_finder/__main__.py", line 201, in <lambda>
    sorted_data = sorted(reader, key=lambda d: float(d["affinity"]),
KeyError: 'affinity'
```

When trying to re-run after exception raised:

```
(venv)erkghlerngm44:~/workspace/r-anime-soulmate-finder (master) $ python3 -m soulmate_finder USER --ftf 15 --buffer-size 1024
Retrieving comment ids for FTF: Free Talk Fridays - Week of September 08, 2017 (6yr7ff)
...
Retrieving comment ids for FTF: Free Talk Fridays - Week of June 02, 2017 (6eqwxj)
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/workspace/r-anime-soulmate-finder/soulmate_finder/__main__.py", line 293, in <module>
    main(comments, **vars(args))
  File "/home/ubuntu/workspace/r-anime-soulmate-finder/soulmate_finder/__main__.py", line 152, in main
    user = row["reddit"]
KeyError: 'reddit'
```

**Options:**

* See what's causing `file.tell()` to eval `True` when we don't want it to be `True`, and patch up
* Replace the `if file.tell():` with something like `if file.read().startswith(",".join(const.HEADERS)):` (which is a bit messy but should do the job), which will eval to `False` if no headers, and will write them in.

**Comment by erkghlerngm44** [comment]
Hmmmm...

* Can't reproduce and don't know *how* to reproduce
* The only way I know to "fix" it would be to take the `if file.read().startswith(",".join(const.HEADERS)):` suggestion, and modify it (because we're opening it in `bytes` mode and it doesn't like plain strings being written to file) to make `if file.read().startswith(b",".join([x.encode() for x in const.HEADERS])):`, which is some ugly stuff. 
`csv.Sniffer.has_header` can't help here, as `unicodecsv` doesn't support it.
* Even if I do come up with something that looks nice and works well, the problem is writing it to file when there's already csv rows in there (which can happen because the above got raised, but then again, I can't repro to confirm), as the header won't automatically get written in to row 1, but appended to the end of the file due to the file being opened up with `a+b`. I'd have to perform some dodgy operations to get it to insert into the correct place.

I guess the only thing that can be done is to write the headers in manually.

![](https://i.imgur.com/gEOKk0P.jpg)

**Comment by erkghlerngm44** [comment]
Closing. Will reopen if I think of something...

**Comment by erkghlerngm44** [comment]
I am an idiot. It's not because `file.tell()` evals to `True`, it's because the file doesn't get flushed when the headers *do* get written in...
